### ISSUE TITLE
Outside bounds of window

### ISSUE THREAD

**Issue by BlinksTale** [davidjohnoliver/CodeConnections#13]
Hopefully not a duplicate issue, I didn't see anything on this, but the nodes are currently scrolling on Windows 10 VS22 outside the bounds of the window itself. I'd love if it all stayed in the Code Connections window/frame. These will block basic windows items like the top right close and minimize buttons. Really enjoying the product so far, so I figure this stuff is worth mentioning!
<img width="1669" alt="codeConnectionsOutsideBounds" src="https://user-images.githubusercontent.com/1028407/214744416-b616fe95-1015-4429-a66b-1d1e10a78d3b.png">

**Comment by davidjohnoliver** [comment]
Thanks for the report! This should be fixed in the next release.
